require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'agthorse' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'agthorseTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!('Flipper' => '0.80.0')
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

target 'agthorse-tvOS' do
  # Pods for agthorse-tvOS

  target 'agthorse-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
